### ISSUE TITLE
Contrast problem with yellow search highlight 

### ISSUE THREAD

**Issue by marciomazza** [marciomazza/vim-brogrammer-theme#6]
It seems the yellow background for search highlight is not working well for some other syntaxes.

Here's how it looks like now:
![problem with yellow search](https://cloud.githubusercontent.com/assets/579665/9110938/715e6e2c-3c18-11e5-912a-c25a1d5af6cd.png)

Here's how it looks in sublime. It's red with white foreground. (Note the in sublime only one occurrence is highlighted):
![screenshot from 2015-08-06 08 59 32](https://cloud.githubusercontent.com/assets/579665/9111139/35487ba6-3c1a-11e5-9fe1-89dd586ef402.png)

**Comment by magnunleno** [comment]
Proposed a fix to make it look like Sublime (background and foreground).

About only highlighting only the first occurrence, it's a "VIM thing" not a "theme thing", and I believe it can't be turned off.
